apiVersion: apps/v1
kind: Deployment
metadata:
  name: habit-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: habit-tracker
  template:
    metadata:
      labels:
        app: habit-tracker
    spec:
      containers:
        - name: app
          image: habit-tracker:latest
